### ISSUE TITLE
should have a unique "key" prop

### ISSUE THREAD

**Issue by AlexandruMares** [web3ui/web3uikit#775]
Warning: Each child in a list should have a unique "key" prop. See https://reactjs.org/link/warning-keys for more information.
    at span
    at button
    at O2 (webpack-internal:///./node_modules/@web3uikit/core/dist/index.js:1991:6)
    at ButtonBase (webpack-internal:///./node_modules/@web3uikit/core/dist/index.js:5386:3)
    at Suspense
    at Button (webpack-internal:///./node_modules/@web3uikit/core/dist/index.js:5476:9)
    at div
    at div
    at AppBar (webpack-internal:///./src/layouts/AppBar.js:52:62)
    at div
    at Layout (webpack-internal:///./src/layouts/Layout.js:26:26)
    at Index
    at MyApp (webpack-internal:///./pages/_app.js:17:27)
    at ErrorBoundary (webpack-internal:///./node_modules/next/dist/compiled/@next/react-dev-overlay/dist/client.js:8:20740)
    at ReactDevOverlay (webpack-internal:///./node_modules/next/dist/compiled/@next/react-dev-overlay/dist/client.js:8:23632)
    at Container (webpack-internal:///./node_modules/next/dist/client/index.js:71:9)
    at AppContainer (webpack-internal:///./node_modules/next/dist/client/index.js:592:26)
    at Root (webpack-internal:///./node_modules/next/dist/client/index.js:703:27)

**Comment by AbhinavMV** [comment]
Hey @AlexandruMares 
TY for using the kit and for feedback 😄 
Do you have a code or example, so that i can replicate this warning 
Just a normal button is not giving this warning to me.

**Comment by AbhinavMV** [comment]
TY @AlexandruMares 
Was able to replicate the bug 🙌🏻 
TY for using the kit and feedback

**Comment by AbhinavMV** [comment]
Closed by #806
